{% set name = "celeries" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/celeries-{{ version }}.tar.gz
  sha256: fbb519702a763451b43d441949b81878131ecd427bef7930f7ebbe2999b0f885

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.16
    - mpmath >=1.0

test:
  imports:
    - celeries
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://gitlab.unige.ch/delisle/celeries
  summary: Celestial mechanics series
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
